/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_ASSIGN_H_RPCGEN
#define _RPC_ASSIGN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sortArray {
	int l1[5];
	int l2[5];
	int res[10];
};
typedef struct sortArray sortArray;

struct complxNo {
	int real1;
	int img1;
	int real2;
	int img2;
	int real;
	int img;
};
typedef struct complxNo complxNo;

#define RPC_PROG 0x31111111
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define hostName 1
extern  char ** hostname_1(void *, CLIENT *);
extern  char ** hostname_1_svc(void *, struct svc_req *);
#define mergeSort 2
extern  sortArray * mergesort_1(sortArray *, CLIENT *);
extern  sortArray * mergesort_1_svc(sortArray *, struct svc_req *);
#define encryptEcho 3
extern  char ** encryptecho_1(char **, CLIENT *);
extern  char ** encryptecho_1_svc(char **, struct svc_req *);
#define listFiles 4
extern  char ** listfiles_1(void *, CLIENT *);
extern  char ** listfiles_1_svc(void *, struct svc_req *);
#define addComplx 5
extern  complxNo * addcomplx_1(complxNo *, CLIENT *);
extern  complxNo * addcomplx_1_svc(complxNo *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define hostName 1
extern  char ** hostname_1();
extern  char ** hostname_1_svc();
#define mergeSort 2
extern  sortArray * mergesort_1();
extern  sortArray * mergesort_1_svc();
#define encryptEcho 3
extern  char ** encryptecho_1();
extern  char ** encryptecho_1_svc();
#define listFiles 4
extern  char ** listfiles_1();
extern  char ** listfiles_1_svc();
#define addComplx 5
extern  complxNo * addcomplx_1();
extern  complxNo * addcomplx_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sortArray (XDR *, sortArray*);
extern  bool_t xdr_complxNo (XDR *, complxNo*);

#else /* K&R C */
extern bool_t xdr_sortArray ();
extern bool_t xdr_complxNo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_ASSIGN_H_RPCGEN */
