/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_Assign.h"

bool_t
xdr_sortArray (XDR *xdrs, sortArray *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 5  + 5  + 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->l1, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->l2, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->res, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->l1;
					i < 5; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->l2;
					i < 5; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->res;
					i < 10; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 5  + 5  + 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->l1, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->l2, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->res, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->l1;
					i < 5; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->l2;
					i < 5; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->res;
					i < 10; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->l1, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->l2, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->res, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_complxNo (XDR *xdrs, complxNo *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->real1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->img1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->real2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->img2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->real))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->img))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->real1);
			IXDR_PUT_LONG(buf, objp->img1);
			IXDR_PUT_LONG(buf, objp->real2);
			IXDR_PUT_LONG(buf, objp->img2);
			IXDR_PUT_LONG(buf, objp->real);
			IXDR_PUT_LONG(buf, objp->img);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->real1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->img1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->real2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->img2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->real))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->img))
				 return FALSE;
		} else {
			objp->real1 = IXDR_GET_LONG(buf);
			objp->img1 = IXDR_GET_LONG(buf);
			objp->real2 = IXDR_GET_LONG(buf);
			objp->img2 = IXDR_GET_LONG(buf);
			objp->real = IXDR_GET_LONG(buf);
			objp->img = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->real1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->img1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->real2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->img2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->real))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->img))
		 return FALSE;
	return TRUE;
}
