/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_Assign.h"


void
rpc_prog_1(char *host) {
    CLIENT *clnt;
    char **result_1;
    char *hostname_1_arg;
    sortArray *result_2;
    sortArray mergesort_1_arg;
    char **result_3;
    char *encryptecho_1_arg;
    char **result_4;
    char *listfiles_1_arg;
    complxNo *result_5;
    complxNo addcomplx_1_arg;

#ifndef    DEBUG
    clnt = clnt_create(host, RPC_PROG, RPC_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif    /* DEBUG */

    int ch, i;

    while (1) {
        //Menu for different operation
        printf("\n********Welcome to RPC Program ********\n");
        printf("1. Get hostname\n");
        printf("2. Merge Sort\n");
        printf("3. Encrypted Echo\n");
        printf("4. List all files\n");
        printf("5. Add complex number\n");
        printf("6. Exit\n");
        printf("Enter your choice:");
        scanf("%d", &ch);

        switch (ch) {
            case 1:
                //Get the server host name
                result_1 = hostname_1((void *) &hostname_1_arg, clnt);
                if (result_1 == (char **) NULL) {
                    clnt_perror(clnt, "call failed");
                } else {
                    printf("The host name is: %s\n", *result_1);
                }
                break;

            case 2:
                //Sort the 2 unsorted list into 1 sorted array
                printf("Enter the element of 1st array: ");
                for (i = 0; i < 5; i++) {
                    scanf("%d", &mergesort_1_arg.l1[i]);
                }
                printf("Enter the element of 2nd array: ");
                for (i = 0; i < 5; i++) {
                    scanf("%d", &mergesort_1_arg.l2[i]);
                }

                //rpc call to sort the lists
                result_2 = mergesort_1(&mergesort_1_arg, clnt);
                if (result_2 == (sortArray *) NULL) {
                    clnt_perror(clnt, "call failed");
                } else {
                    printf("The Merged sorted list is\n");
                    for (i = 0; i < 10; i++) {
                        printf("%d\t", result_2->res[i]);
                    }
                }
                printf("\n");
                break;

            case 3:;
                //Encrypt the string entered by the user
                char echo_str[1024];

                getchar();
                printf("Enter the string:");
                scanf("%[^\n]s", &echo_str);

                encryptecho_1_arg = echo_str;

                //rpc call to encrypt the string
                result_3 = encryptecho_1(&encryptecho_1_arg, clnt);
                if (result_3 == (char **) NULL) {
                    clnt_perror(clnt, "call failed");
                } else {
                    printf("The encrypted string is: %s\n", *result_3);
                }
                break;

            case 4:
                //Get the list of all the files in the directory
                result_4 = listfiles_1((void *) &listfiles_1_arg, clnt);
                if (result_4 == (char **) NULL) {
                    clnt_perror(clnt, "call failed");
                } else {
                    printf("The list of files is: %s\n", *result_4);
                }
                break;

            case 5:
                //Add 2 complex numbers
                printf("Enter the 1st real part: ");
                scanf("%d", &addcomplx_1_arg.real1);
                printf("Enter the 1st img part: ");
                scanf("%d", &addcomplx_1_arg.img1);

                printf("Enter the 2nd real part: ");
                scanf("%d", &addcomplx_1_arg.real2);
                printf("Enter the 2nd img part: ");
                scanf("%d", &addcomplx_1_arg.img2);

                //rpc call to add 2 complex numbers
                result_5 = addcomplx_1(&addcomplx_1_arg, clnt);
                if (result_5 == (complxNo *) NULL) {
                    clnt_perror(clnt, "call failed");
                } else {
                    printf("The addition of 2 complex no is : %d + (%d)i\n", result_5->real, result_5->img);
                }
                break;

            case 6:
                //Exit the client
                exit(0);
                break;

            default:
                printf("Enter valid Option!!\n");
                break;

        }//switch
    }//while

#ifndef    DEBUG
    clnt_destroy(clnt);
#endif     /* DEBUG */
}


int
main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    rpc_prog_1(host);
    exit(0);
}
