/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_Assign.h"
#include<dirent.h>

char **
hostname_1_svc(void *argp, struct svc_req *rqstp) {
    static char *result;

    printf("\n****Host Name****\n");
    char *hostname;
    hostname = (char *) malloc(sizeof(char) * (1024));
    //get the server host name
    gethostname(hostname, 1023);

    result = hostname;
    printf("The Hostname: %s\n", result);

    return &result;
}

sortArray *
mergesort_1_svc(sortArray *argp, struct svc_req *rqstp) {
    static sortArray result;

    printf("\n****Merge Sort****\n");
    int res[10], i, j = 0, key;

    //Copy both the unsorted array in 1 array
    for (i = 0; i < 5; i++)
        result.res[j++] = argp->l1[i];
    for (i = 0; i < 5; i++)
        result.res[j++] = argp->l2[i];

    //Perform insertion sort on the single array to sort
    for (i = 1; i < 10; i++) {
        key = result.res[i];
        j = i - 1;

        while (j >= 0 && result.res[j] > key) {
            result.res[j + 1] = result.res[j];
            j = j - 1;
        }
        result.res[j + 1] = key;
    }

    //Display the sorted array
    printf("The sorted list is:\n");
    for (i = 0; i < 10; i++) {
        printf("%d\t", result.res[i]);
    }
    printf("\n");
    return &result;
}

char **
encryptecho_1_svc(char **argp, struct svc_req *rqstp) {
    static char *result;

    printf("\n****Encrypted Echo****\n");
    printf("The input string is: %s\n", *argp);

    int len = strlen(*argp);
    char *outputEcho = (char *) malloc(sizeof(char) * (len));
    int i;

    //Encrypt the entered string using encryption technique
    for (i = 0; i < strlen(*argp); i++) {
        outputEcho[i] = (char) ((((*argp)[i] * 3) + 10 ));

    }

    result = outputEcho;
    printf("The Encrypted string is: %s\n", result);


    return &result;
}

char **
listfiles_1_svc(void *argp, struct svc_req *rqstp) {
    static char *result;

    printf("\n****List of Files****\n");
    char *files = (char *) malloc(sizeof(char) * 1024);
    DIR *d;
    struct dirent *dir;
    //open the current directory
    d = opendir(".");
    if (d) {
        //read each file from the directory
        while ((dir = readdir(d)) != NULL) {
            sprintf(files + strlen(files), "%s\n", dir->d_name);

        }

        //close the directory
        closedir(d);
    }

    result = files;
    printf("The list of files is: %s\n", result);
    return &result;
}

complxNo *
addcomplx_1_svc(complxNo *argp, struct svc_req *rqstp) {
    static complxNo result;

    printf("\n****Addition of Complex Number****\n");
    printf("The 1st complex no is: %d + (%d)i\n", argp->real1, argp->img1);
    printf("The 2nd complex no is: %d + (%d)i\n", argp->real2, argp->img2);
    int real, img;

    //Add the real and imaginary part of the complex numbers
    real = argp->real1 + argp->real2;
    img = argp->img1 + argp->img2;

    result.real = real;
    result.img = img;

    printf("The addition of 2 complex no is : %d + (%d)i\n", result.real, result.img);
    return &result;
}
